[build-system]
requires = [
    "setuptools >= 42",
    "wheel >= 0.29.0",
    "setuptools_scm[toml] >= 3.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "dirty-tag"

[tool.pytest.ini_options]
addopts = "-rsx --tb=short"
testpaths = "tests"

[tool.coverage.run]
source = ["typeguard"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:"
]

[tool.isort]
src_paths = ["src"]
profile = "black"
skip_gitignore = true

[tool.flake8]
max-line-length = 99
ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.7"
ignore_missing_imports = true
#strict = true
pretty = true
